language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - build_test

sudo: false

php:
  # - 5.3
  - 5.6

jobs:
  include:
#     - stage: test
#       # 環境変数の定義
#       env:
#         - WP_VERSION=latest WP_MULTISITE=0
#         # - WP_VERSION=3.7 WP_MULTISITE=0
#         - WP_VERSION=4.7.3 WP_MULTISITE=0
#       matrix:
#         include:
#           - php: 5.3
#             env: WP_VERSION=latest WP_MULTISITE=1
#       before_script:
#         - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
#         - export PATH="$HOME/.composer/vendor/bin:$PATH"
#         - |
#           if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
#             composer global require "phpunit/phpunit=5.6.*"
#           else
#             composer global require "phpunit/phpunit=4.8.*"
#           fi
#       script: 
#         # - phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
#         - phpunit
#     # - # stage name not required, will continue to use `test`
#     #   script: ./test 2
    - stage: deploy
      # 環境変数の定義
      env:
        global:
          - GIT_COMMITTER_NAME=travis-ci
          - GIT_COMMITTER_EMAIL=kurudrive@gmail.com
          - GIT_AUTHOR_NAME=travis-ci
          - GIT_AUTHOR_EMAIL=kurudrive@gmail.com
          - secure: "OIbsIUESLHI5IZ4AXhrufCukweIG0CNBvBtfXuzdUcQwi3LXHoGhGGubOccHMYRYH86+UjH9p3w3Euhz/5W6nDmyokDOha7gwSecMAgQoLBFncrh/T+ntlUi+zdW5w5I6kw8ZsmaJ1dZsrgNmkVxNwM/qrMCZsVSmwh3FnXpHFCOhhse2CGwfKtFz7YEC31JyizgxroiGv9QVTSFhacLuqFqhlMA6Uc6PB/RwAUf0ra9jt1DItYakKcamwg1cbyiROLtPwc83QY3TCOFkoFMVj/3wqn+HCUaoqgj5LQcFh2quHVn0u8xjebGdqyhD3v3sttZYRaT5/Up4CB/kRJ8bRB4a/eMR4tY89zjs8RVLo9HjbEAPO89HNgAg4Yce7y1iZOR1uc+q94tupzovq6PX4AtsC7ZAfnRdoGIskLs668satlAK6XQSwsIhNESLrVPjqG0Sr6CKPyw+RWLvsEpfQl8/OsoQpJCEfo/1ioGA2iNuZxuKfTJKSctZO3NAkG79V36ENfxWmM3PnAbYOaSkuZAr1rUGn0lZSj+dwclMTRNKN1dTUbq/yJZh5LdRKg+iT7OahhRP5AecG/Hd8v/dlGOAy500G6BUAXdP1Kfpop0cXpv8NMjpiFF2ldRGcnxb7DVQ/XsH21oTAaPhMzTmoIoWV3ZmZttpwrpCURhoz0="
      before_script:
        - nvm install 4.2
        - npm install
      script: 
        - find . \( -name '*.php' \) -exec php -lf {} \;
      after_success:
        - bash ../bin/deploy.sh

  # - |
  #   composer global require wp-coding-standards/wpcs
  #   phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs

